// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutFeaturesSplit from '@/components/sections/about/AboutFeaturesSplit';
import { Clock, DollarSign, Shield, Star, TrendingUp, Zap } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
        <SectionErrorBoundary name="about">
              <AboutFeaturesSplit
          tag="About Our Agency"
          title="Enterprise Growth Through Intelligent AI"
          description="We bridge the gap between complex data and actionable marketing results. Our AI platform processes billions of data points to optimize your SEO performance in real-time."
          items={[
            {
              icon: Zap,
              title: "Automated Strategy",
              description: "AI-driven execution for rapid scalability.",
            },
            {
              icon: Shield,
              title: "Data Transparency",
              description: "Real-time reporting on ROI and traffic metrics.",
            },
            {
              icon: Star,
              title: "Enterprise Focus",
              description: "Built for complex multi-market campaigns.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/business-data-analytics_23-2151957121.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
