// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqSplitMedia from '@/components/sections/faq/FaqSplitMedia';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
        <SectionErrorBoundary name="faq">
              <FaqSplitMedia
          tag="Common Questions"
          title="Everything You Need To Know"
          description="Get clear, concise answers to your questions about AI-driven SEO scaling."
          items={[
            {
              question: "How quickly do you see results?",
              answer: "Clients typically see initial growth signals within 30-60 days due to our AI-accelerated indexing techniques.",
            },
            {
              question: "Is this a whitelabel solution?",
              answer: "Yes, we work with agencies and internal marketing teams as a seamless, high-performance extension.",
            },
            {
              question: "What tools do you integrate with?",
              answer: "We integrate with all major analytics, CRM, and marketing automation platforms currently used by enterprise firms.",
            },
            {
              question: "What industries do you serve?",
              answer: "We specialize in B2B SaaS, E-commerce, Finance, and complex enterprise organizations where scaling organic traffic is paramount.",
            },
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/dynamic-data-visualization-3d_23-2151904326.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
