// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "features-bento" section.

import React from 'react';
import FeaturesRevealCardsBento from '@/components/sections/features/FeaturesRevealCardsBento';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function FeaturesBentoSection(): React.JSX.Element {
  return (
    <div id="features-bento" data-section="features-bento">
        <SectionErrorBoundary name="features-bento">
              <FeaturesRevealCardsBento
          tag="Core Capabilities"
          title="An Intelligence-First Marketing Engine"
          description="Seven pillars of performance that redefine what's possible for your organic search growth."
          items={[
            {
              title: "Predictive SEO",
              description: "Forecast traffic patterns before they happen.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/programming-background-with-html_23-2150038862.jpg",
            },
            {
              title: "Automated Link Building",
              description: "High-quality acquisition powered by AI.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/closeup-african-american-entrepreneur-analyzing-company-profit_482257-20207.jpg",
            },
            {
              title: "Content Intelligence",
              description: "Generate high-converting search content.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/woman-sitting-bed-with-laptop-phone_23-2148751554.jpg",
            },
            {
              title: "Competitive Monitoring",
              description: "Real-time tracking of search rivals.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/data-center-computer-scientist-wheelchair-using-ai-node-tree-software_482257-126137.jpg",
            },
            {
              title: "Tech SEO Audits",
              description: "Automated fixes for technical debt.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/business-graphs-figures-laptop-left-open-desk-empty-office_482257-84546.jpg",
            },
            {
              title: "ROI Attribution",
              description: "Direct tie-back to business revenue.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/businesswoman-looking-company-charts_482257-124401.jpg",
            },
            {
              title: "Global Scaling",
              description: "Automated multi-language localization.",
              href: "#",
              imageSrc: "http://img.b2bpic.net/free-photo/programmer-developing-software-large-computer-screen_53876-101149.jpg",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
