// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroCenteredLogos from '@/components/sections/hero/HeroCenteredLogos';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
        <SectionErrorBoundary name="hero">
              <HeroCenteredLogos
          avatarsSrc={[
            "http://img.b2bpic.net/free-photo/attractive-armenian-guy-with-hat-yellow-black-wall_181624-32940.jpg",
            "http://img.b2bpic.net/free-photo/smiley-businesswoman-posing-outdoors_23-2148767054.jpg",
            "http://img.b2bpic.net/free-photo/portrait-smiling-indian-businessman-office_1262-3271.jpg",
            "http://img.b2bpic.net/free-photo/inspiring-new-boss_1098-93.jpg",
          ]}
          avatarText="Trusted by 500+ Enterprises"
          title="AI-Powered SEO That Scales Your Revenue"
          description="Enterprise marketing teams trust us to automate strategy, accelerate rankings, and deliver measurable growth. Proven results for Fortune 500 and scaling startups alike."
          primaryButton={{
            text: "Schedule Your Strategy Call",
            href: "#contact",
          }}
          secondaryButton={{
            text: "View Case Studies",
            href: "#about",
          }}
          names={[
            "Google",
            "Microsoft",
            "Salesforce",
            "Hubspot",
            "Shopify",
            "Stripe",
            "Amazon",
          ]}
          imageSrc="http://img.b2bpic.net/free-photo/3d-render-modern-technology-background-with-plexus-design_1048-14928.jpg"
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
