/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import HeroBackgroundSlot from "@/components/ui/HeroBackgroundSlot";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import AvatarGroup from "@/components/ui/AvatarGroup";

const avatarsSrc = [
  "http://img.b2bpic.net/free-photo/attractive-armenian-guy-with-hat-yellow-black-wall_181624-32940.jpg",
  "http://img.b2bpic.net/free-photo/smiley-businesswoman-posing-outdoors_23-2148767054.jpg",
  "http://img.b2bpic.net/free-photo/portrait-smiling-indian-businessman-office_1262-3271.jpg",
  "http://img.b2bpic.net/free-photo/inspiring-new-boss_1098-93.jpg"
];
const primaryButton = {
  text: "Schedule Your Strategy Call",
  href: "#contact"
};
const secondaryButton = {
  text: "View Case Studies",
  href: "#about"
};
const names = [
  "Google",
  "Microsoft",
  "Salesforce",
  "Hubspot",
  "Shopify",
  "Stripe",
  "Amazon"
];

type HeroCenteredLogosProps = {
  avatarsSrc: string[];
  avatarText: string;
  title: string;
  description: string;
  primaryButton: { text: string; href: string };
  secondaryButton: { text: string; href: string };
  names: string[];
  hideMedia?: boolean;
  textAnimation: "slide-up" | "fade-blur" | "fade";
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

const HeroInline = () => {
  return (
    <section aria-label="Hero section" className="relative h-svh flex flex-col mb-20">
      <HeroBackgroundSlot />
      {!undefined && (
        <div className="absolute inset-0 z-0">
          <ImageOrVideo imageSrc={"http://img.b2bpic.net/free-photo/3d-render-modern-technology-background-with-plexus-design_1048-14928.jpg"} className="size-full object-cover" />
          <div className="absolute inset-0 bg-background/80" />
        </div>
      )}

      <div className="relative z-10 flex-1 flex items-center justify-center">
        <div className="flex flex-col items-center gap-3 pt-8 w-content-width mx-auto text-center">
          <AvatarGroup avatarsSrc={avatarsSrc} label={"Trusted by 500+ Enterprises"} size="lg" />

          <TextAnimation
            text={"AI-Powered SEO That Scales Your Revenue"}
            variant={"slide-up"}
            gradientText={true}
            tag="h1"
            className="md:max-w-8/10 text-7xl 2xl:text-8xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"Enterprise marketing teams trust us to automate strategy, accelerate rankings, and deliver measurable growth. Proven results for Fortune 500 and scaling startups alike."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-balance"
          />

          <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
            <Button text={primaryButton.text} href={primaryButton.href} variant="primary" />
            <Button text={secondaryButton.text} href={secondaryButton.href} variant="secondary" animationDelay={0.1} />
          </div>
        </div>
      </div>

      <div className="relative z-10 w-content-width mx-auto pb-8 overflow-hidden mask-fade-x">
        <div className="flex w-max animate-marquee-horizontal" style={{ animationDuration: "30s" }}>
          {[...names, ...names, ...names, ...names].map((name, index) => (
            <div key={index} className="shrink-0 mx-3 px-4 py-2 card rounded">
              <span className="text-xl font-semibold whitespace-nowrap text-foreground/75">{name}</span>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default function HeroSection() {
  return (
    <div data-webild-section="hero" data-section="hero" id="hero">
      <HeroInline />
    </div>
  );
}
