// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "metrics" section.

import React from 'react';
import MetricsIconCards from '@/components/sections/metrics/MetricsIconCards';
import { Clock, DollarSign, Shield, Star, TrendingUp, Zap } from "lucide-react";
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function MetricsSection(): React.JSX.Element {
  return (
    <div id="metrics" data-section="metrics">
        <SectionErrorBoundary name="metrics">
              <MetricsIconCards
          tag="Results Driven"
          title="Proven Performance Metrics"
          description="The numbers don't lie. Our partners see immediate, scalable returns on their organic investments."
          metrics={[
            {
              icon: TrendingUp,
              title: "Average Traffic Increase",
              value: "145%",
            },
            {
              icon: DollarSign,
              title: "ROI Improvement",
              value: "210%",
            },
            {
              icon: Clock,
              title: "Strategy Automation",
              value: "80%",
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
