// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "pricing" section.

import React from 'react';
import PricingSplitCards from '@/components/sections/pricing/PricingSplitCards';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function PricingSection(): React.JSX.Element {
  return (
    <div id="pricing" data-section="pricing">
        <SectionErrorBoundary name="pricing">
              <PricingSplitCards
          tag="Transparent Pricing"
          title="Designed For Growth at Any Scale"
          description="Clear tiers for teams that require enterprise reliability and high-end results."
          plans={[
            {
              tag: "Growth",
              price: "$4,900",
              period: "/mo",
              description: "Perfect for growing midmarket companies.",
              primaryButton: {
                text: "Start Growth",
                href: "#contact",
              },
              featuresTitle: "Included Features",
              features: [
                "Advanced SEO Audit",
                "AI Content Strategy",
                "Weekly Reporting",
                "Dedicated Support",
              ],
            },
            {
              tag: "Enterprise",
              price: "$12,500",
              period: "/mo",
              description: "For large organizations with complex needs.",
              primaryButton: {
                text: "Contact Sales",
                href: "#contact",
              },
              featuresTitle: "Included Features",
              features: [
                "Full AI Stack Access",
                "Multi-Market Scaling",
                "Custom API Integration",
                "24/7 Priority Support",
              ],
            },
          ]}
          textAnimation="slide-up"
        />
        </SectionErrorBoundary>
      </div>
  );
}
