/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const steps = [
  {
    tag: "Phase 01",
    title: "Data Discovery",
    subtitle: "Deep analysis of your current stack.",
    description: "Uncovering hidden opportunities with proprietary AI mapping.",
    imageSrc: "http://img.b2bpic.net/free-photo/5g-connection-technology-background-with-man-using-futuristic-virtual-screen-digital-remix_53876-108511.jpg"
  },
  {
    tag: "Phase 02",
    title: "Strategy Execution",
    subtitle: "Precision-targeted optimizations.",
    description: "Implementing data-backed adjustments across your entire digital footprint.",
    imageSrc: "http://img.b2bpic.net/free-photo/close-up-computer-peripherals-server-room-desk_482257-118044.jpg"
  },
  {
    tag: "Phase 03",
    title: "Growth Acceleration",
    subtitle: "Ongoing intelligent refinements.",
    description: "Continuous monitoring and iterative improvements for sustained growth.",
    imageSrc: "http://img.b2bpic.net/free-photo/arrangement-with-colorful-shapes_23-2148879428.jpg"
  }
];

type StepItem = {
  tag: string;
  title: string;
  subtitle: string;
  description: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesDetailedStepsProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  steps: StepItem[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const ProcessInline = () => {
  return (
    <section aria-label="Features detailed steps section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Methodology"}</p>
          </div>

          <TextAnimation
            text={"Scaling Organic Traffic In 3 Steps"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"A proven, data-centric process designed for enterprise-grade complexity."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="flex flex-col w-content-width mx-auto gap-5">
          {steps.map((step, index) => {
            const stepNumber = String(index + 1).padStart(2, "0");
            return (
              <ScrollReveal
                variant="slide-up"
                key={step.title}
                className="flex flex-col md:flex-row justify-between 2xl:w-8/10 mx-auto gap-6 p-6 md:p-10 card rounded overflow-hidden"
              >
                <div className="flex flex-col justify-between w-full md:w-1/2">
                  <div className="flex flex-col gap-2">
                    <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                      <p>{step.tag}</p>
                    </div>
                    <h3 className="text-7xl md:text-8xl font-semibold leading-[1.15] text-balance">{step.title}</h3>
                  </div>
                  <div className="block md:hidden w-full h-px my-5 bg-accent/20" />
                  <div className="flex flex-col gap-2">
                    <h4 className="text-2xl md:text-3xl font-semibold leading-snug text-balance">
                      {step.title === "Strategy Execution" ? (
                        <a href="https://totaldesign.rs" target="_blank" rel="noopener noreferrer" className="hover:underline underline">
                          {step.subtitle}
                        </a>
                      ) : (
                        step.subtitle
                      )}
                    </h4>
                    <p className="text-base md:text-lg leading-snug text-balance">{step.description}</p>
                  </div>
                </div>
                <div className="flex flex-col w-full md:w-35/100 gap-10">
                  <span className="hidden md:block self-end text-7xl md:text-8xl font-semibold text-accent">{stepNumber}</span>
                  <div className={cls("aspect-square rounded overflow-hidden", index % 2 === 0 ? "rotate-3" : "-rotate-3")}>
                    <ImageOrVideo imageSrc={step.imageSrc} videoSrc={step.videoSrc} />
                  </div>
                </div>
              </ScrollReveal>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default function ProcessSection() {
  return (
    <div data-webild-section="process" data-section="process" id="process">
      <ProcessInline />
    </div>
  );
}
