// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "social-proof" section.

import React from 'react';
import SocialProofMarquee from '@/components/sections/social-proof/SocialProofMarquee';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function SocialProofSection(): React.JSX.Element {
  return (
    <div id="social-proof" data-section="social-proof">
        <SectionErrorBoundary name="social-proof">
              <SocialProofMarquee
          tag="Trusted By Industry Leaders"
          title="Driving Results For The World's Best Brands"
          description="We partner with companies that demand precision, scale, and intelligence in their marketing stack."
          names={[
            "Google",
            "Amazon",
            "Microsoft",
            "Stripe",
            "Salesforce",
            "Shopify",
            "Hubspot",
            "Intel",
          ]}
          textAnimation="fade"
        />
        </SectionErrorBoundary>
      </div>
  );
}
