// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "testimonials" section.

import React from 'react';
import TestimonialTrustCard from '@/components/sections/testimonial/TestimonialTrustCard';
import SectionErrorBoundary from "@/components/ui/SectionErrorBoundary";

export default function TestimonialsSection(): React.JSX.Element {
  return (
    <div id="testimonials" data-section="testimonials">
        <SectionErrorBoundary name="testimonials">
              <TestimonialTrustCard
          quote="This AI-driven strategy has transformed our organic search from a secondary channel into a core revenue driver. Absolute game changer."
          rating={5}
          author="Sarah Miller, CMO at GrowthCo"
          avatars={[
            {
              name: "Sarah Miller",
              imageSrc: "http://img.b2bpic.net/free-photo/portrait-young-afro-businessman-wearing-shirt-black-suit-glasses-looking-front-while-standing-beige-wall_158595-7638.jpg",
            },
            {
              name: "David Kim",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-man-white-long-sleeve-tee-portrait_53876-97108.jpg",
            },
            {
              name: "Emily Rose",
              imageSrc: "http://img.b2bpic.net/free-photo/business-woman-banner-concept-with-copy-space_23-2149601533.jpg",
            },
            {
              name: "John Doe",
              imageSrc: "http://img.b2bpic.net/free-photo/smiling-man-suit-looking-camera_23-2148112202.jpg",
            },
            {
              name: "Jane Smith",
              imageSrc: "http://img.b2bpic.net/free-photo/side-view-business-woman-posing_23-2149457762.jpg",
            },
            {
              name: "Mike Ross",
              imageSrc: "http://img.b2bpic.net/free-photo/executive-assistant-multinational-company-work-big-business-project_482257-113916.jpg",
            },
          ]}
          textAnimation="fade-blur"
        />
        </SectionErrorBoundary>
      </div>
  );
}
